services:
  - type: web
    name: apps-server
    env: node
    plan: starter
    region: oregon
    buildCommand: pnpm install && pnpm nx build server
    startCommand: node dist/apps/server/main.js
    runtime: node
    branch: main
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: SUPABASE_URL
        sync: true
