name: build-artifacts
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Install Vercel
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
 
      - name: Build the app
        run: |
             pnpm build  

      - name: Deploy to Render
        run: |
            curl -fsSL https://render.com/deploy/specific_deploy_key  
        env:
            RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} 



