name: build_upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build the App
        run: pnpm nx run web:build --prod

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: dist/apps/web  

