name: deploy-render

on:
  workflow_run:
    workflows: ['build-test']
    types:
      - completed

jobs:
  deploy-render:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: server-build

      - name: Deploy to Render
        run: |
          curl -fsSL ${{secrets.RENDER_WEBHOOK}}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
