name: deploy-vercel

on:
  workflow_run:
    workflows: ['build-test']
    types:
      - completed

jobs:
  deploy-vercel:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build

      - name: Install Vercel CLI
        run: npm install -global vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
